### ISSUE TITLE
DataType.Create fails for new Umbraco 7 property editors due to Guid parsing

### ISSUE THREAD

**Issue by katerd** [dev-mag/uFluent#20]
FluentDataTypeService creates a Guid from a string - this fails for new Umbraco 7 property editors as they no longer use Guid.

```
System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)
   at System.Guid.TryParseGuidWithNoStyle(String guidString, GuidResult& result)
   at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result)
   at System.Guid..ctor(String g)
   at uFluent.Persistence.FluentDataTypeService.Create(String name, String propertyEditor, DataTypeDatabaseType databaseType)
   at uFluent.DataType.Create(String name, String propertyEditor, DataTypeDatabaseType databaseType)
   at mag.escapeLounges.core.uFluent.Migrate.Migrations.LinkPickerDataType_Create.Migrate() in c:\code\mag.escapelounges\src\mag.escapeLounges.core\uFluent.Migrate\Migrations\LinkPickerDataType_Create.cs:line 11
   at uFluent.Migrate.MigrationProcessor.ProcessMigration(IUmbracoMigration umbracoMigration)
   at uFluent.Migrate.MigrationProcessor.ProcessMigrations(IEnumerable`1 migrations)
```

**Comment by katerd** [comment]
Related to #16 and #6
