### ISSUE TITLE
Tag DataType

### ISSUE THREAD

**Issue by mike-w-kelly** [dev-mag/uFluent#21]
# Summary

I'm trying to add a custom tag datatype with the following migration based on the example project

var tagGroup = DataType.Create("Kb Article Tags", PropertyEditor.Tags,   DataTypeDatabaseType.Ntext).Save();
            tagGroup.SetTagDataTypePreValues("Kb Article Tags", StorageType.Csv).Save();

The migration runs fine and I can see the Data Type in the back office, but when I try to access it I get the following error which suggests there is an error with the PropertyEditor mapping.

Any ideas?
# Error

Received an error from the server
Failed to retrieve data for data type id 5130

Could not find property editor with alias 4023E540-92F5-11DD-AD8B-0800200C9A66
Exception Details:
System.InvalidOperationException: Could not find property editor with alias 4023E540-92F5-11DD-AD8B-0800200C9A66
Stacktrace:

at Umbraco.Web.Models.Mapping.PreValueDisplayResolver.Convert(IDataTypeDefinition source)

   at Umbraco.Web.Models.Mapping.PreValueDisplayResolver.ResolveCore(IDataTypeDefinition source)

   at AutoMapper.ValueResolver`2.Resolve(ResolutionResult source)

   at AutoMapper.PropertyMap.<ResolveValue>b__6(ResolutionResult current, IValueResolver resolver)

   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)

   at AutoMapper.PropertyMap.ResolveValue(ResolutionContext context)

   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap)

**Comment by anD1332** [comment]
Hi Mike, 

I've had a look at the uFluent issue this morning.  If you set the property editor to "Umbraco.Tags" in the initial create statement it will work.  We need to change the constants so they are not GUID based but if you put the property editor name in there instead of PropertyEditor.Tags it will create the data type

An example of this would be 

``` C#
DataType.Create("Article Tags", "Umbraco.Tags", DataTypeDatabaseType.Ntext)
        .SetTagDataTypePreValues("Article Tags", StorageType.Csv).Save();
```

This is a workaround for the moment, we will look at getting the issue with the property editor constants fixed.

Thanks
Andy

**Comment by mike-w-kelly** [comment]
Thanks Andy, I'll give that a go later today.

Cheers,
Mike

**Comment by mike-w-kelly** [comment]
Workaround works, thanks
